(READRULES '*gist-clause-trees-for-input*
'(
   ; Direct gist clauses from schema
   1 (Why 1 I not 1 sleeping well ?)
      2 (*sleep-poorly-input*) (0 :subtrees)
   1 (How will I know if my pain medication is working ?)
      2 (*medicine-working-input*) (0 :subtrees)
   1 (Can I have a stronger pain medication ?)
      2 (*medicine-request-input*) (0 :subtrees)
   1 (What do my test results mean ?)
      2 (*test-results-input*) (0 :subtrees)
   1 (What is my prognosis ?)
      2 (*prognosis-input*) (0 :subtrees)
   1 (What are my options for treatment ?)
      2 (*treatment-option-input*) (0 :subtrees)
   1 (Do I need chemotherapy ?)
      2 (*chemotherapy-input*) (0 :subtrees)
   1 (Should I get comfort care ?)
      2 (*comfort-care-input*) (0 :subtrees)
   1 (What should I tell my family ?)
      2 (*tell-family-input*) (0 :subtrees)

   ; Gist clauses from potential sub-dialogues
   1 (My pain has recently been getting worse \.)
      2 (*pain-input*) (0 :subtrees)
   1 (I am here alone \.)
      2 (*anyone-here-with-you-input*) (0 :subtrees)
   1 (I got my diagnosis after visiting a lung doctor \.)
      2 (*diagnosis-details-input*) (0 :subtrees)
   1 (I have lost 1 weight \.)
      2 (*diagnosis-details-input*) (0 :subtrees)
   1 (I had radiation treatment for five weeks \.)
      2 (*radiation-input*) (0 :subtrees)
   1 (I was feeling a little better after radiation \.)
      2 (*radiation-input*) (0 :subtrees)
   1 (Do you think radiation will help ?)
      2 (*radiation-input-verification-input*) (0 :subtrees)
   1 (Do I need chemotherapy ?)
      2 (*chemotherapy-input*) (0 :subtrees)
   1 (Do you think chemotherapy will help ?)
      2 (*chemotherapy-input*) (0 :subtrees)
   1 (What are the side effects of chemotherapy ?)
      2 (*chemotherapy-details-input*) (0 :subtrees)
   1 (How does chemotherapy work ?)
      2 (*chemotherapy-details-input*) (0 :subtrees)
   1 (I have not been sleeping well \.)
      2 (*sleep-poorly-input*) (0 :subtrees)
   1 (I have been fatigued \.)
      2 (*energy-input*) (0 :subtrees)
   1 (I have had trouble concentrating \.)
      2 (*energy-input*) (0 :subtrees)
   1 (I feel mildly depressed \.)
      2 (*energy-input*) (0 :subtrees)
   1 (Will an antidepressant help me with my pain ?)
      2 (*energy-input*) (0 :subtrees)
   1 (Should I try medication before I try therapy ?)
      2 (*energy-input*) (0 :subtrees)
   1 (I don\'t have allergies to any medicine \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (I am only taking Lortab to treat my pain \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (I am taking Cozar to help with blood pressure \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (Taking the Lortab more frequently helps \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (Why isn\'t the pain medication working anymore ?)
      2 (*medicine-working-input*) (0 :subtrees)
   1 (What are the side effects of stronger pain medication ?)
      2 (*medicine-side-effects-input*) (0 :subtrees)
   1 (Can I get addicted to narcotics ?)
      2 (*medicine-side-effects-addiction-input*) (0 :subtrees)
   1 (I would like a refill of medicine \.)
      2 (*medicine-request-input*) (0 :subtrees)
   1 (Has the cancer gotten worse ?)
      2 (*cancer-worse-input*) (0 :subtrees)
   1 (Are you sure the cancer has not gotten worse ?)
      2 (*cancer-worse-verification-input*) (0 :subtrees)
   1 (What is my prognosis ?)
      2 (*prognosis-input*) (0 :subtrees)
   1 (What happens if I do not do chemotherapy ?)
      2 (*treatment-option-input*) (0 :subtrees)
   1 (How does comfort care work ?)
      2 (*comfort-care-input*) (0 :subtrees)
   1 (Are you sure that I do not need comfort care ?)
      2 (*comfort-care-verification-input*) (0 :subtrees)
      
   1 (0)
      2 (*general-input*) (0 :subtrees)
))
