(READRULES '*gist-clause-trees-for-input*
'(
   1 (My pain has recently been getting worse \.)
      2 (*pain-input*) (0 :subtrees)
   1 (I am here alone \.)
      2 (*anyone-here-with-you-input*) (0 :subtrees)
   1 (I got my diagnosis after visiting a lung doctor \.)
      2 (*diagnosis-details-input*) (0 :subtrees)
   1 (I had radiation treatment for five weeks \.)
      2 (*radiation-input*) (0 :subtrees)
   1 (Do I need chemotherapy ?)
      2 (*chemotherapy-input*) (0 :subtrees)
   1 (What are the side effects of chemotherapy ?)
      2 (*chemotherapy-details-input*) (0 :subtrees)
   1 (I have not been sleeping well \.)
      2 (*sleep-input*) (0 :subtrees)
   1 (I have been fatigued \.)
      2 (*energy-input*) (0 :subtrees)
   1 (I have had trouble concentrating \.)
      2 (*energy-input*) (0 :subtrees)
   1 (I don\'t have allergies to any medicine \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (I am only taking Lortab to treat my pain \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (I am taking Cozar to help with blood pressure \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (Why isn\'t the pain medication working anymore ?)
      2 (*medicine-input*) (0 :subtrees)
   1 (Can you tell me about the side effects ?)
      2 (*side-effects-input*) (0 :subtrees)

   ; The following two will need modification
   1 (I would like a refill of medicine \.)
      2 (*medicine-input*) (0 :subtrees)
   1 (What is my prognosis ?)
      2 (*prognosis-input*) (0 :subtrees)
      
   1 (0)
      2 (*general-input*) (0 :subtrees)
))