(READRULES '*gist-clause-trees-for-input*
   '(
      1 (2 what 1 your name 1)
         2 (*name-input*) (0 :subtrees)
      1 (2 do 1 have 2 spatial question 1) 
         2 (*spatial-question-input*) (0 :subtrees)
      1 (0 do 1 want 2 resume 1)
         2 (*request-input*) (0 :subtrees)
      1 (do you understand 1 concept 1)
         2 (*understand-concept-input*) (0 :subtrees)
      1 (do you want to make 1 bigger example of 1 concept 1)
         2 (*bigger-example-input*) (0 :subtrees)
      1 (0)
         2 (*spatial-question-input*) (0 :subtrees)
))
